apiVersion: propertymapping.authentik.crossplane.io/v1alpha1
kind: LDAP
metadata:
  annotations:
    meta.upbound.io/example-id: propertymapping/v1alpha1/ldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    expression: return ldap.get('sAMAccountName')
    name: custom-field
    objectField: username
