//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flow.
func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Flow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowInitParameters) DeepCopyInto(out *FlowInitParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(string)
		**out = **in
	}
	if in.Background != nil {
		in, out := &in.Background, &out.Background
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(bool)
		**out = **in
	}
	if in.DeniedAction != nil {
		in, out := &in.DeniedAction, &out.DeniedAction
		*out = new(string)
		**out = **in
	}
	if in.Designation != nil {
		in, out := &in.Designation, &out.Designation
		*out = new(string)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowInitParameters.
func (in *FlowInitParameters) DeepCopy() *FlowInitParameters {
	if in == nil {
		return nil
	}
	out := new(FlowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowList) DeepCopyInto(out *FlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Flow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowList.
func (in *FlowList) DeepCopy() *FlowList {
	if in == nil {
		return nil
	}
	out := new(FlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowObservation) DeepCopyInto(out *FlowObservation) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(string)
		**out = **in
	}
	if in.Background != nil {
		in, out := &in.Background, &out.Background
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(bool)
		**out = **in
	}
	if in.DeniedAction != nil {
		in, out := &in.DeniedAction, &out.DeniedAction
		*out = new(string)
		**out = **in
	}
	if in.Designation != nil {
		in, out := &in.Designation, &out.Designation
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowObservation.
func (in *FlowObservation) DeepCopy() *FlowObservation {
	if in == nil {
		return nil
	}
	out := new(FlowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowParameters) DeepCopyInto(out *FlowParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(string)
		**out = **in
	}
	if in.Background != nil {
		in, out := &in.Background, &out.Background
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityMode != nil {
		in, out := &in.CompatibilityMode, &out.CompatibilityMode
		*out = new(bool)
		**out = **in
	}
	if in.DeniedAction != nil {
		in, out := &in.DeniedAction, &out.DeniedAction
		*out = new(string)
		**out = **in
	}
	if in.Designation != nil {
		in, out := &in.Designation, &out.Designation
		*out = new(string)
		**out = **in
	}
	if in.Layout != nil {
		in, out := &in.Layout, &out.Layout
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowParameters.
func (in *FlowParameters) DeepCopy() *FlowParameters {
	if in == nil {
		return nil
	}
	out := new(FlowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSpec) DeepCopyInto(out *FlowSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSpec.
func (in *FlowSpec) DeepCopy() *FlowSpec {
	if in == nil {
		return nil
	}
	out := new(FlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowStatus) DeepCopyInto(out *FlowStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowStatus.
func (in *FlowStatus) DeepCopy() *FlowStatus {
	if in == nil {
		return nil
	}
	out := new(FlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBinding) DeepCopyInto(out *StageBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBinding.
func (in *StageBinding) DeepCopy() *StageBinding {
	if in == nil {
		return nil
	}
	out := new(StageBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingInitParameters) DeepCopyInto(out *StageBindingInitParameters) {
	*out = *in
	if in.EvaluateOnPlan != nil {
		in, out := &in.EvaluateOnPlan, &out.EvaluateOnPlan
		*out = new(bool)
		**out = **in
	}
	if in.InvalidResponseAction != nil {
		in, out := &in.InvalidResponseAction, &out.InvalidResponseAction
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ReEvaluatePolicies != nil {
		in, out := &in.ReEvaluatePolicies, &out.ReEvaluatePolicies
		*out = new(bool)
		**out = **in
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingInitParameters.
func (in *StageBindingInitParameters) DeepCopy() *StageBindingInitParameters {
	if in == nil {
		return nil
	}
	out := new(StageBindingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingList) DeepCopyInto(out *StageBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StageBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingList.
func (in *StageBindingList) DeepCopy() *StageBindingList {
	if in == nil {
		return nil
	}
	out := new(StageBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StageBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingObservation) DeepCopyInto(out *StageBindingObservation) {
	*out = *in
	if in.EvaluateOnPlan != nil {
		in, out := &in.EvaluateOnPlan, &out.EvaluateOnPlan
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InvalidResponseAction != nil {
		in, out := &in.InvalidResponseAction, &out.InvalidResponseAction
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ReEvaluatePolicies != nil {
		in, out := &in.ReEvaluatePolicies, &out.ReEvaluatePolicies
		*out = new(bool)
		**out = **in
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingObservation.
func (in *StageBindingObservation) DeepCopy() *StageBindingObservation {
	if in == nil {
		return nil
	}
	out := new(StageBindingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingParameters) DeepCopyInto(out *StageBindingParameters) {
	*out = *in
	if in.EvaluateOnPlan != nil {
		in, out := &in.EvaluateOnPlan, &out.EvaluateOnPlan
		*out = new(bool)
		**out = **in
	}
	if in.InvalidResponseAction != nil {
		in, out := &in.InvalidResponseAction, &out.InvalidResponseAction
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ReEvaluatePolicies != nil {
		in, out := &in.ReEvaluatePolicies, &out.ReEvaluatePolicies
		*out = new(bool)
		**out = **in
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingParameters.
func (in *StageBindingParameters) DeepCopy() *StageBindingParameters {
	if in == nil {
		return nil
	}
	out := new(StageBindingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingSpec) DeepCopyInto(out *StageBindingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingSpec.
func (in *StageBindingSpec) DeepCopy() *StageBindingSpec {
	if in == nil {
		return nil
	}
	out := new(StageBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageBindingStatus) DeepCopyInto(out *StageBindingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageBindingStatus.
func (in *StageBindingStatus) DeepCopy() *StageBindingStatus {
	if in == nil {
		return nil
	}
	out := new(StageBindingStatus)
	in.DeepCopyInto(out)
	return out
}
