apiVersion: authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: authentik/v1alpha1/application
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: example-app
    protocolProvider: ${authentik_provider_oauth2.name.id}

---

apiVersion: policy.authentik.crossplane.io/v1alpha1
kind: Binding
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/application
  labels:
    testing.upbound.io/example-name: app-access
  name: app-access
spec:
  forProvider:
    order: 0
    policy: ${authentik_policy_expression.policy.id}
    target: ${authentik_application.name.uuid}

---

apiVersion: policy.authentik.crossplane.io/v1alpha1
kind: Expression
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/application
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    expression: return True
    name: example

---

apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: OAuth2
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/application
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    authorizationFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    clientId: example-app
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: example-app
