apiVersion: authentik.crossplane.io/v1alpha1
kind: EventTransport
metadata:
  annotations:
    meta.upbound.io/example-id: authentik/v1alpha1/eventtransport
  labels:
    testing.upbound.io/example-name: transport
  name: transport
spec:
  forProvider:
    mode: webhook
    name: my-transport
    sendOnce: true
    webhookUrl: https://foo.bar
