apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: OAuth2
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/oauth2
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    clientId: grafana
    name: grafana

---

apiVersion: application.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/oauth2
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test app
    protocolProvider: ${authentik_provider_oauth2.name.id}
