apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: Radius
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/radius
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    authorizationFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    clientNetworks: 10.10.0.0/24
    name: radius-app
    sharedSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: application.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/radius
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: radius-app
    protocolProviderSelector:
      matchLabels:
        testing.upbound.io/example-name: name
