apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: SAML
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/saml
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    acsUrl: http://localhost
    authorizationFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    name: test-app

---

apiVersion: application.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/saml
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    protocolProviderSelector:
      matchLabels:
        testing.upbound.io/example-name: name
