apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: SCIM
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/scim
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    propertyMappings:
    - ${data.authentik_property_mapping_scim.user.id}
    propertyMappingsGroup:
    - ${data.authentik_property_mapping_scim.group.id}
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: http://localhost
