apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: directory/v1alpha1/user
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: User
    username: user

---

apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: directory/v1alpha1/user
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: group-name
