apiVersion: stage.authentik.crossplane.io/v1alpha1
kind: Captcha
metadata:
  annotations:
    meta.upbound.io/example-id: stage/v1alpha1/captcha
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: captcha
    privateKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    publicKey: bar
