apiVersion: stage.authentik.crossplane.io/v1alpha1
kind: Deny
metadata:
  annotations:
    meta.upbound.io/example-id: stage/v1alpha1/deny
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: deny
