apiVersion: stage.authentik.crossplane.io/v1alpha1
kind: Password
metadata:
  annotations:
    meta.upbound.io/example-id: stage/v1alpha1/password
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backends:
    - authentik.core.auth.InbuiltBackend
    name: test-stage
