apiVersion: stage.authentik.crossplane.io/v1alpha1
kind: PromptField
metadata:
  annotations:
    meta.upbound.io/example-id: stage/v1alpha1/promptfield
  labels:
    testing.upbound.io/example-name: field
  name: field
spec:
  forProvider:
    fieldKey: username
    label: Username
    type: username
