apiVersion: application.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: application/v1alpha1/application
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: example-app
    protocolProvider: ${authentik_provider_oauth2.name.id}

---

apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: OAuth2
metadata:
  annotations:
    meta.upbound.io/example-id: application/v1alpha1/application
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    authorizationFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    clientId: example-app
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: example-app
