/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthenticatorTOTPInitParameters struct {

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (Number) Defaults to 6.
	// Defaults to `6`.
	Digits *float64 `json:"digits,omitempty" tf:"digits,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AuthenticatorTOTPObservation struct {

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (Number) Defaults to 6.
	// Defaults to `6`.
	Digits *float64 `json:"digits,omitempty" tf:"digits,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AuthenticatorTOTPParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (Number) Defaults to 6.
	// Defaults to `6`.
	// +kubebuilder:validation:Optional
	Digits *float64 `json:"digits,omitempty" tf:"digits,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// AuthenticatorTOTPSpec defines the desired state of AuthenticatorTOTP
type AuthenticatorTOTPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthenticatorTOTPParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthenticatorTOTPInitParameters `json:"initProvider,omitempty"`
}

// AuthenticatorTOTPStatus defines the observed state of AuthenticatorTOTP.
type AuthenticatorTOTPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthenticatorTOTPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorTOTP is the Schema for the AuthenticatorTOTPs API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type AuthenticatorTOTP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AuthenticatorTOTPSpec   `json:"spec"`
	Status AuthenticatorTOTPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorTOTPList contains a list of AuthenticatorTOTPs
type AuthenticatorTOTPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthenticatorTOTP `json:"items"`
}

// Repository type metadata.
var (
	AuthenticatorTOTP_Kind             = "AuthenticatorTOTP"
	AuthenticatorTOTP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthenticatorTOTP_Kind}.String()
	AuthenticatorTOTP_KindAPIVersion   = AuthenticatorTOTP_Kind + "." + CRDGroupVersion.String()
	AuthenticatorTOTP_GroupVersionKind = CRDGroupVersion.WithKind(AuthenticatorTOTP_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthenticatorTOTP{}, &AuthenticatorTOTPList{})
}
