/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthenticatorWebAuthnInitParameters struct {

	// (String)
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty" tf:"authenticator_attachment,omitempty"`

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	ResidentKeyRequirement *string `json:"residentKeyRequirement,omitempty" tf:"resident_key_requirement,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	UserVerification *string `json:"userVerification,omitempty" tf:"user_verification,omitempty"`
}

type AuthenticatorWebAuthnObservation struct {

	// (String)
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty" tf:"authenticator_attachment,omitempty"`

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	ResidentKeyRequirement *string `json:"residentKeyRequirement,omitempty" tf:"resident_key_requirement,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	UserVerification *string `json:"userVerification,omitempty" tf:"user_verification,omitempty"`
}

type AuthenticatorWebAuthnParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty" tf:"authenticator_attachment,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	// +kubebuilder:validation:Optional
	ResidentKeyRequirement *string `json:"residentKeyRequirement,omitempty" tf:"resident_key_requirement,omitempty"`

	// (String) Defaults to preferred.
	// Defaults to `preferred`.
	// +kubebuilder:validation:Optional
	UserVerification *string `json:"userVerification,omitempty" tf:"user_verification,omitempty"`
}

// AuthenticatorWebAuthnSpec defines the desired state of AuthenticatorWebAuthn
type AuthenticatorWebAuthnSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthenticatorWebAuthnParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthenticatorWebAuthnInitParameters `json:"initProvider,omitempty"`
}

// AuthenticatorWebAuthnStatus defines the observed state of AuthenticatorWebAuthn.
type AuthenticatorWebAuthnStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthenticatorWebAuthnObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorWebAuthn is the Schema for the AuthenticatorWebAuthns API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type AuthenticatorWebAuthn struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AuthenticatorWebAuthnSpec   `json:"spec"`
	Status AuthenticatorWebAuthnStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorWebAuthnList contains a list of AuthenticatorWebAuthns
type AuthenticatorWebAuthnList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthenticatorWebAuthn `json:"items"`
}

// Repository type metadata.
var (
	AuthenticatorWebAuthn_Kind             = "AuthenticatorWebAuthn"
	AuthenticatorWebAuthn_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthenticatorWebAuthn_Kind}.String()
	AuthenticatorWebAuthn_KindAPIVersion   = AuthenticatorWebAuthn_Kind + "." + CRDGroupVersion.String()
	AuthenticatorWebAuthn_GroupVersionKind = CRDGroupVersion.WithKind(AuthenticatorWebAuthn_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthenticatorWebAuthn{}, &AuthenticatorWebAuthnList{})
}
