/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthenticatorDuoInitParameters struct {

	// (String)
	APIHostname *string `json:"apiHostname,omitempty" tf:"api_hostname,omitempty"`

	// (String)
	AdminIntegrationKey *string `json:"adminIntegrationKey,omitempty" tf:"admin_integration_key,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AuthenticatorDuoObservation struct {

	// (String)
	APIHostname *string `json:"apiHostname,omitempty" tf:"api_hostname,omitempty"`

	// (String)
	AdminIntegrationKey *string `json:"adminIntegrationKey,omitempty" tf:"admin_integration_key,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String)
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type AuthenticatorDuoParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	APIHostname *string `json:"apiHostname,omitempty" tf:"api_hostname,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AdminIntegrationKey *string `json:"adminIntegrationKey,omitempty" tf:"admin_integration_key,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	AdminSecretKeySecretRef *v1.SecretKeySelector `json:"adminSecretKeySecretRef,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive)
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef v1.SecretKeySelector `json:"clientSecretSecretRef" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	ConfigureFlow *string `json:"configureFlow,omitempty" tf:"configure_flow,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// AuthenticatorDuoSpec defines the desired state of AuthenticatorDuo
type AuthenticatorDuoSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthenticatorDuoParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthenticatorDuoInitParameters `json:"initProvider,omitempty"`
}

// AuthenticatorDuoStatus defines the observed state of AuthenticatorDuo.
type AuthenticatorDuoStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthenticatorDuoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorDuo is the Schema for the AuthenticatorDuos API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type AuthenticatorDuo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiHostname) || (has(self.initProvider) && has(self.initProvider.apiHostname))",message="spec.forProvider.apiHostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientSecretSecretRef)",message="spec.forProvider.clientSecretSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AuthenticatorDuoSpec   `json:"spec"`
	Status AuthenticatorDuoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticatorDuoList contains a list of AuthenticatorDuos
type AuthenticatorDuoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthenticatorDuo `json:"items"`
}

// Repository type metadata.
var (
	AuthenticatorDuo_Kind             = "AuthenticatorDuo"
	AuthenticatorDuo_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthenticatorDuo_Kind}.String()
	AuthenticatorDuo_KindAPIVersion   = AuthenticatorDuo_Kind + "." + CRDGroupVersion.String()
	AuthenticatorDuo_GroupVersionKind = CRDGroupVersion.WithKind(AuthenticatorDuo_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthenticatorDuo{}, &AuthenticatorDuoList{})
}
