/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserWriteInitParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	CreateUsersAsInactive *bool `json:"createUsersAsInactive,omitempty" tf:"create_users_as_inactive,omitempty"`

	// (String)
	CreateUsersGroup *string `json:"createUsersGroup,omitempty" tf:"create_users_group,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to create_when_required.
	// Defaults to `create_when_required`.
	UserCreationMode *string `json:"userCreationMode,omitempty" tf:"user_creation_mode,omitempty"`

	// (String) Defaults to “.
	// Defaults to “.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type UserWriteObservation struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	CreateUsersAsInactive *bool `json:"createUsersAsInactive,omitempty" tf:"create_users_as_inactive,omitempty"`

	// (String)
	CreateUsersGroup *string `json:"createUsersGroup,omitempty" tf:"create_users_group,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to create_when_required.
	// Defaults to `create_when_required`.
	UserCreationMode *string `json:"userCreationMode,omitempty" tf:"user_creation_mode,omitempty"`

	// (String) Defaults to “.
	// Defaults to “.
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

type UserWriteParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	CreateUsersAsInactive *bool `json:"createUsersAsInactive,omitempty" tf:"create_users_as_inactive,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CreateUsersGroup *string `json:"createUsersGroup,omitempty" tf:"create_users_group,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to create_when_required.
	// Defaults to `create_when_required`.
	// +kubebuilder:validation:Optional
	UserCreationMode *string `json:"userCreationMode,omitempty" tf:"user_creation_mode,omitempty"`

	// (String) Defaults to “.
	// Defaults to “.
	// +kubebuilder:validation:Optional
	UserPathTemplate *string `json:"userPathTemplate,omitempty" tf:"user_path_template,omitempty"`
}

// UserWriteSpec defines the desired state of UserWrite
type UserWriteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserWriteParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserWriteInitParameters `json:"initProvider,omitempty"`
}

// UserWriteStatus defines the observed state of UserWrite.
type UserWriteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserWriteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// UserWrite is the Schema for the UserWrites API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type UserWrite struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   UserWriteSpec   `json:"spec"`
	Status UserWriteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserWriteList contains a list of UserWrites
type UserWriteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserWrite `json:"items"`
}

// Repository type metadata.
var (
	UserWrite_Kind             = "UserWrite"
	UserWrite_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserWrite_Kind}.String()
	UserWrite_KindAPIVersion   = UserWrite_Kind + "." + CRDGroupVersion.String()
	UserWrite_GroupVersionKind = CRDGroupVersion.WithKind(UserWrite_Kind)
)

func init() {
	SchemeBuilder.Register(&UserWrite{}, &UserWriteList{})
}
