/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UserLogoutInitParameters struct {

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type UserLogoutObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type UserLogoutParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// UserLogoutSpec defines the desired state of UserLogout
type UserLogoutSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserLogoutParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserLogoutInitParameters `json:"initProvider,omitempty"`
}

// UserLogoutStatus defines the observed state of UserLogout.
type UserLogoutStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserLogoutObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// UserLogout is the Schema for the UserLogouts API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type UserLogout struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   UserLogoutSpec   `json:"spec"`
	Status UserLogoutStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserLogoutList contains a list of UserLogouts
type UserLogoutList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserLogout `json:"items"`
}

// Repository type metadata.
var (
	UserLogout_Kind             = "UserLogout"
	UserLogout_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserLogout_Kind}.String()
	UserLogout_KindAPIVersion   = UserLogout_Kind + "." + CRDGroupVersion.String()
	UserLogout_GroupVersionKind = CRDGroupVersion.WithKind(UserLogout_Kind)
)

func init() {
	SchemeBuilder.Register(&UserLogout{}, &UserLogoutList{})
}
