apiVersion: flow.authentik.crossplane.io/v1alpha1
kind: StageBinding
metadata:
  annotations:
    meta.upbound.io/example-id: flow/v1alpha1/stagebinding
  labels:
    testing.upbound.io/example-name: dummy-flow
  name: dummy-flow
spec:
  forProvider:
    order: 0
    stage: ${authentik_stage_dummy.name.id}
    target: ${authentik_flow.flow.uuid}

---

apiVersion: flow.authentik.crossplane.io/v1alpha1
kind: Flow
metadata:
  annotations:
    meta.upbound.io/example-id: flow/v1alpha1/stagebinding
  labels:
    testing.upbound.io/example-name: flow
  name: flow
spec:
  forProvider:
    designation: authorization
    name: test-flow
    title: Test flow
