apiVersion: application.authentik.crossplane.io/v1alpha1
kind: ProviderOAuth2
metadata:
  name: hello-crossplane
spec:
  forProvider:
    name: upbound
    clientId: foo-bar-123
    authorizationFlowRef:
      name: my-authorization
  providerConfigRef:
    name: default
