apiVersion: application.authentik.crossplane.io/v1alpha1
kind: ProviderOAuth2
metadata:
  name: hello-crossplane
spec:
  forProvider:
    name: upbound
    clientId: upjet-provider-template
    authorizationFlowRef:
      name: default-provider-authorization-explicit-consent
  providerConfigRef:
    name: default
