/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OAuth2InitParameters struct {

	// (String) Defaults to minutes=1.
	// Defaults to `minutes=1`.
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Defaults to minutes=10.
	// Defaults to `minutes=10`.
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (String)
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Defaults to confidential.
	// Defaults to `confidential`.
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String) Defaults to per_provider.
	// Defaults to `per_provider`.
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) Defaults to days=30.
	// Defaults to `days=30`.
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// (String) Defaults to hashed_user_id.
	// Defaults to `hashed_user_id`.
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

type OAuth2Observation struct {

	// (String) Defaults to minutes=1.
	// Defaults to `minutes=1`.
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Defaults to minutes=10.
	// Defaults to `minutes=10`.
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (String)
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Defaults to confidential.
	// Defaults to `confidential`.
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String) Defaults to per_provider.
	// Defaults to `per_provider`.
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// (List of String)
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) Defaults to days=30.
	// Defaults to `days=30`.
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// (String) Defaults to hashed_user_id.
	// Defaults to `hashed_user_id`.
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

type OAuth2Parameters struct {

	// (String) Defaults to minutes=1.
	// Defaults to `minutes=1`.
	// +kubebuilder:validation:Optional
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Defaults to minutes=10.
	// Defaults to `minutes=10`.
	// +kubebuilder:validation:Optional
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/MacroPower/provider-authentik/apis/authentik/v1alpha1.Flow
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("uuid",true)
	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in authentik to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.Reference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in authentik to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.Selector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) Generated.
	// Generated.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v1.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Defaults to confidential.
	// Defaults to `confidential`.
	// +kubebuilder:validation:Optional
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String) Defaults to per_provider.
	// Defaults to `per_provider`.
	// +kubebuilder:validation:Optional
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// +kubebuilder:validation:Optional
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +crossplane:generate:reference:type=github.com/MacroPower/provider-authentik/apis/authentik/v1alpha1.ScopeMapping
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to ScopeMapping in authentik to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.Reference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of ScopeMapping in authentik to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.Selector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// (List of String)
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) Defaults to days=30.
	// Defaults to `days=30`.
	// +kubebuilder:validation:Optional
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// (String) Defaults to hashed_user_id.
	// Defaults to `hashed_user_id`.
	// +kubebuilder:validation:Optional
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

// OAuth2Spec defines the desired state of OAuth2
type OAuth2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OAuth2Parameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OAuth2InitParameters `json:"initProvider,omitempty"`
}

// OAuth2Status defines the observed state of OAuth2.
type OAuth2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OAuth2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// OAuth2 is the Schema for the OAuth2s API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type OAuth2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OAuth2Spec   `json:"spec"`
	Status OAuth2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OAuth2List contains a list of OAuth2s
type OAuth2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OAuth2 `json:"items"`
}

// Repository type metadata.
var (
	OAuth2_Kind             = "OAuth2"
	OAuth2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OAuth2_Kind}.String()
	OAuth2_KindAPIVersion   = OAuth2_Kind + "." + CRDGroupVersion.String()
	OAuth2_GroupVersionKind = CRDGroupVersion.WithKind(OAuth2_Kind)
)

func init() {
	SchemeBuilder.Register(&OAuth2{}, &OAuth2List{})
}
