/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EventTransportInitParameters struct {

	// (String)
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	SendOnce *bool `json:"sendOnce,omitempty" tf:"send_once,omitempty"`

	// (String)
	WebhookMapping *string `json:"webhookMapping,omitempty" tf:"webhook_mapping,omitempty"`

	// (String)
	WebhookURL *string `json:"webhookUrl,omitempty" tf:"webhook_url,omitempty"`
}

type EventTransportObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	SendOnce *bool `json:"sendOnce,omitempty" tf:"send_once,omitempty"`

	// (String)
	WebhookMapping *string `json:"webhookMapping,omitempty" tf:"webhook_mapping,omitempty"`

	// (String)
	WebhookURL *string `json:"webhookUrl,omitempty" tf:"webhook_url,omitempty"`
}

type EventTransportParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	SendOnce *bool `json:"sendOnce,omitempty" tf:"send_once,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	WebhookMapping *string `json:"webhookMapping,omitempty" tf:"webhook_mapping,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	WebhookURL *string `json:"webhookUrl,omitempty" tf:"webhook_url,omitempty"`
}

// EventTransportSpec defines the desired state of EventTransport
type EventTransportSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EventTransportParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EventTransportInitParameters `json:"initProvider,omitempty"`
}

// EventTransportStatus defines the observed state of EventTransport.
type EventTransportStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EventTransportObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EventTransport is the Schema for the EventTransports API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type EventTransport struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EventTransportSpec   `json:"spec"`
	Status EventTransportStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EventTransportList contains a list of EventTransports
type EventTransportList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EventTransport `json:"items"`
}

// Repository type metadata.
var (
	EventTransport_Kind             = "EventTransport"
	EventTransport_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EventTransport_Kind}.String()
	EventTransport_KindAPIVersion   = EventTransport_Kind + "." + CRDGroupVersion.String()
	EventTransport_GroupVersionKind = CRDGroupVersion.WithKind(EventTransport_Kind)
)

func init() {
	SchemeBuilder.Register(&EventTransport{}, &EventTransportList{})
}
