/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DummyInitParameters struct {

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Result *bool `json:"result,omitempty" tf:"result,omitempty"`

	// (Number) Defaults to 30.
	// Defaults to `30`.
	WaitMax *float64 `json:"waitMax,omitempty" tf:"wait_max,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	WaitMin *float64 `json:"waitMin,omitempty" tf:"wait_min,omitempty"`
}

type DummyObservation struct {

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Result *bool `json:"result,omitempty" tf:"result,omitempty"`

	// (Number) Defaults to 30.
	// Defaults to `30`.
	WaitMax *float64 `json:"waitMax,omitempty" tf:"wait_max,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	WaitMin *float64 `json:"waitMin,omitempty" tf:"wait_min,omitempty"`
}

type DummyParameters struct {

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	Result *bool `json:"result,omitempty" tf:"result,omitempty"`

	// (Number) Defaults to 30.
	// Defaults to `30`.
	// +kubebuilder:validation:Optional
	WaitMax *float64 `json:"waitMax,omitempty" tf:"wait_max,omitempty"`

	// (Number) Defaults to 5.
	// Defaults to `5`.
	// +kubebuilder:validation:Optional
	WaitMin *float64 `json:"waitMin,omitempty" tf:"wait_min,omitempty"`
}

// DummySpec defines the desired state of Dummy
type DummySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DummyParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DummyInitParameters `json:"initProvider,omitempty"`
}

// DummyStatus defines the observed state of Dummy.
type DummyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DummyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Dummy is the Schema for the Dummys API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Dummy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DummySpec   `json:"spec"`
	Status DummyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DummyList contains a list of Dummys
type DummyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Dummy `json:"items"`
}

// Repository type metadata.
var (
	Dummy_Kind             = "Dummy"
	Dummy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Dummy_Kind}.String()
	Dummy_KindAPIVersion   = Dummy_Kind + "." + CRDGroupVersion.String()
	Dummy_GroupVersionKind = CRDGroupVersion.WithKind(Dummy_Kind)
)

func init() {
	SchemeBuilder.Register(&Dummy{}, &DummyList{})
}
