/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EventMatcherInitParameters struct {

	// (String)
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String)
	App *string `json:"app,omitempty" tf:"app,omitempty"`

	// (String)
	ClientIP *string `json:"clientIp,omitempty" tf:"client_ip,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String)
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EventMatcherObservation struct {

	// (String)
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String)
	App *string `json:"app,omitempty" tf:"app,omitempty"`

	// (String)
	ClientIP *string `json:"clientIp,omitempty" tf:"client_ip,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EventMatcherParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	App *string `json:"app,omitempty" tf:"app,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ClientIP *string `json:"clientIp,omitempty" tf:"client_ip,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// EventMatcherSpec defines the desired state of EventMatcher
type EventMatcherSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EventMatcherParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EventMatcherInitParameters `json:"initProvider,omitempty"`
}

// EventMatcherStatus defines the observed state of EventMatcher.
type EventMatcherStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EventMatcherObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EventMatcher is the Schema for the EventMatchers API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type EventMatcher struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EventMatcherSpec   `json:"spec"`
	Status EventMatcherStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EventMatcherList contains a list of EventMatchers
type EventMatcherList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EventMatcher `json:"items"`
}

// Repository type metadata.
var (
	EventMatcher_Kind             = "EventMatcher"
	EventMatcher_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EventMatcher_Kind}.String()
	EventMatcher_KindAPIVersion   = EventMatcher_Kind + "." + CRDGroupVersion.String()
	EventMatcher_GroupVersionKind = CRDGroupVersion.WithKind(EventMatcher_Kind)
)

func init() {
	SchemeBuilder.Register(&EventMatcher{}, &EventMatcherList{})
}
